spring:
  datasource:
    url: jdbc:mysql://localhost:3306/filmegreg
    username: root
    password: univille
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
